# Generated by Django 4.2.6 on 2023-10-29 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('villa', '0002_basket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'ordering': ['id']},
        ),
    ]
