# Generated by Django 4.2.6 on 2023-11-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villa', '0003_alter_apartment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='stripe_object_price_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
