# Generated by Django 4.2.6 on 2023-11-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villa', '0004_apartment_stripe_object_price_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
