# Generated by Django 4.2.6 on 2023-11-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preorder',
            old_name='backet_history',
            new_name='basket_history',
        ),
        migrations.AddField(
            model_name='preorder',
            name='stripe_object_price_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
