# Generated by Django 4.2.6 on 2023-11-18 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_backet_history_preorder_basket_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preorder',
            name='stripe_object_price_id',
        ),
    ]
